#
# Derived from
# https://github.com/steveno/ctags/blob/master/.travis.yml
#

language: c

os:
  - linux

compiler:
  - gcc

sudo: true

addons:
  apt:
    packages:
      - lcov
      - procps
      - netcat
before_install:
  - |
    gem install lcoveralls

# Build and run tests. Only with gcc cross compile
script:
  - sudo sh ./check-linux.sh

after_success:
  - |
    (
            for f in /home/travis/.rvm/gems/ruby-2*/gems/lcoveralls-*/lib/lcoveralls/color_formatter.rb; do
                    sed -i -e 's/severity.capitalize!/severity = severity.capitalize/' $f
            done
    ) || :
    lcov -c -b . -d . -o coverage.info && lcoveralls --root . --retry-count 5 coverage.info
