#
# Derived from
# https://github.com/steveno/ctags/blob/master/.travis.yml
#

language: c

os:
  - linux

compiler:
  - gcc

sudo: true

addons:
  apt:
    packages:
      - procps
      - netcat

# Build and run tests. Only with gcc cross compile
script:
  - sudo sh ./check-linux.sh
